title: The Visual Influence on Zebrafish Larval Locomotion through Experimental–Computational Methods
logo: /assets/img/logo.png
description: A senior thesis submitted in partial satisfaction of the requirements for the degree Bachelor of Science in physics.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
