title: The Visual Influence on Zebrafish Larval Locomotion through Experimental–Computational Methods
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
